#!/bin/bash

if [[ $# -eq 0 ]]; then
	help_message_create
fi

while [[ $# -gt 0 ]]; do
	key="$1"
	case $key in
		-n)
			vm_name="$2"
			shift
			shift
			;;
		*)
			echo "Unknown argument: $key"
			exit 1
			;;
	esac
done

virsh dominfo ${vm_name} >/dev/null 2>&1
if [[ $? == 1 ]]; then echo "VM ${vm_name} not exists"; exit 1; fi


virsh destroy ${vm_name}
for i in $(virsh domblklist $vm_name | grep -E "vd[a-z]+" | awk '{print $2}'); do
	echo "Deleting volume $i"
	lvremove -y -q $i
done
virsh undefine ${vm_name}

